/*
Admin API for IDMC

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// RoleStatus Whether the organization's license to use the role is valid or has expired.
type RoleStatus string

// List of roleStatus
const (
	ENABLED RoleStatus = "Enabled"
	DISABLED RoleStatus = "Disabled"
)

// All allowed values of RoleStatus enum
var AllowedRoleStatusEnumValues = []RoleStatus{
	"Enabled",
	"Disabled",
}

func (v *RoleStatus) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := RoleStatus(value)
	for _, existing := range AllowedRoleStatusEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid RoleStatus", value)
}

// NewRoleStatusFromValue returns a pointer to a valid RoleStatus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewRoleStatusFromValue(v string) (*RoleStatus, error) {
	ev := RoleStatus(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for RoleStatus: valid values are %v", v, AllowedRoleStatusEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v RoleStatus) IsValid() bool {
	for _, existing := range AllowedRoleStatusEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to roleStatus value
func (v RoleStatus) Ptr() *RoleStatus {
	return &v
}

type NullableRoleStatus struct {
	value *RoleStatus
	isSet bool
}

func (v NullableRoleStatus) Get() *RoleStatus {
	return v.value
}

func (v *NullableRoleStatus) Set(val *RoleStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableRoleStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableRoleStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRoleStatus(val *RoleStatus) *NullableRoleStatus {
	return &NullableRoleStatus{value: val, isSet: true}
}

func (v NullableRoleStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRoleStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

