/*
Admin API for IDMC

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ApiErrorResponseBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiErrorResponseBody{}

// ApiErrorResponseBody When the REST API encounters an error, it returns a REST API error object.
type ApiErrorResponseBody struct {
	Error ApiError `json:"error"`
}

type _ApiErrorResponseBody ApiErrorResponseBody

// NewApiErrorResponseBody instantiates a new ApiErrorResponseBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiErrorResponseBody(error_ ApiError) *ApiErrorResponseBody {
	this := ApiErrorResponseBody{}
	this.Error = error_
	return &this
}

// NewApiErrorResponseBodyWithDefaults instantiates a new ApiErrorResponseBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiErrorResponseBodyWithDefaults() *ApiErrorResponseBody {
	this := ApiErrorResponseBody{}
	return &this
}

// GetError returns the Error field value
func (o *ApiErrorResponseBody) GetError() ApiError {
	if o == nil {
		var ret ApiError
		return ret
	}

	return o.Error
}

// GetErrorOk returns a tuple with the Error field value
// and a boolean to check if the value has been set.
func (o *ApiErrorResponseBody) GetErrorOk() (*ApiError, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Error, true
}

// SetError sets field value
func (o *ApiErrorResponseBody) SetError(v ApiError) {
	o.Error = v
}

func (o ApiErrorResponseBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiErrorResponseBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["error"] = o.Error
	return toSerialize, nil
}

func (o *ApiErrorResponseBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"error",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiErrorResponseBody := _ApiErrorResponseBody{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApiErrorResponseBody)

	if err != nil {
		return err
	}

	*o = ApiErrorResponseBody(varApiErrorResponseBody)

	return err
}

type NullableApiErrorResponseBody struct {
	value *ApiErrorResponseBody
	isSet bool
}

func (v NullableApiErrorResponseBody) Get() *ApiErrorResponseBody {
	return v.value
}

func (v *NullableApiErrorResponseBody) Set(val *ApiErrorResponseBody) {
	v.value = val
	v.isSet = true
}

func (v NullableApiErrorResponseBody) IsSet() bool {
	return v.isSet
}

func (v *NullableApiErrorResponseBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiErrorResponseBody(val *ApiErrorResponseBody) *NullableApiErrorResponseBody {
	return &NullableApiErrorResponseBody{value: val, isSet: true}
}

func (v NullableApiErrorResponseBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiErrorResponseBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


