/*
Admin API for IDMC

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetRolesResponseBodyItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetRolesResponseBodyItem{}

// GetRolesResponseBodyItem struct for GetRolesResponseBodyItem
type GetRolesResponseBodyItem struct {
	// Role ID.
	Id *string `json:"id,omitempty"`
	// ID of the organization the role belongs to.
	OrgId *string `json:"orgId,omitempty"`
	// User who created the role.
	CreatedBy *string `json:"createdBy,omitempty"`
	// User who last updated the role.
	UpdatedBy *string `json:"updatedBy,omitempty"`
	// Date and time the role was created.
	CreateTime *string `json:"createTime,omitempty"`
	// Date and time the role was last updated.
	UpdateTime *string `json:"updateTime,omitempty"`
	// Name of the role.
	RoleName *string `json:"roleName,omitempty"`
	// Description of the role.
	Description *string `json:"description,omitempty"`
	// Role name displayed in the user interface.
	DisplayName *string `json:"displayName,omitempty"`
	// Description displayed in the user interface.
	DisplayDescription *string `json:"displayDescription,omitempty"`
	// Whether the role is a system-defined role.
	SystemRole *bool `json:"systemRole,omitempty"`
	Status *RoleStatus `json:"status,omitempty"`
	Privileges []RolePrivilegeItem `json:"privileges,omitempty"`
}

// NewGetRolesResponseBodyItem instantiates a new GetRolesResponseBodyItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetRolesResponseBodyItem() *GetRolesResponseBodyItem {
	this := GetRolesResponseBodyItem{}
	return &this
}

// NewGetRolesResponseBodyItemWithDefaults instantiates a new GetRolesResponseBodyItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetRolesResponseBodyItemWithDefaults() *GetRolesResponseBodyItem {
	this := GetRolesResponseBodyItem{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *GetRolesResponseBodyItem) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRolesResponseBodyItem) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *GetRolesResponseBodyItem) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *GetRolesResponseBodyItem) SetId(v string) {
	o.Id = &v
}

// GetOrgId returns the OrgId field value if set, zero value otherwise.
func (o *GetRolesResponseBodyItem) GetOrgId() string {
	if o == nil || IsNil(o.OrgId) {
		var ret string
		return ret
	}
	return *o.OrgId
}

// GetOrgIdOk returns a tuple with the OrgId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRolesResponseBodyItem) GetOrgIdOk() (*string, bool) {
	if o == nil || IsNil(o.OrgId) {
		return nil, false
	}
	return o.OrgId, true
}

// HasOrgId returns a boolean if a field has been set.
func (o *GetRolesResponseBodyItem) HasOrgId() bool {
	if o != nil && !IsNil(o.OrgId) {
		return true
	}

	return false
}

// SetOrgId gets a reference to the given string and assigns it to the OrgId field.
func (o *GetRolesResponseBodyItem) SetOrgId(v string) {
	o.OrgId = &v
}

// GetCreatedBy returns the CreatedBy field value if set, zero value otherwise.
func (o *GetRolesResponseBodyItem) GetCreatedBy() string {
	if o == nil || IsNil(o.CreatedBy) {
		var ret string
		return ret
	}
	return *o.CreatedBy
}

// GetCreatedByOk returns a tuple with the CreatedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRolesResponseBodyItem) GetCreatedByOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedBy) {
		return nil, false
	}
	return o.CreatedBy, true
}

// HasCreatedBy returns a boolean if a field has been set.
func (o *GetRolesResponseBodyItem) HasCreatedBy() bool {
	if o != nil && !IsNil(o.CreatedBy) {
		return true
	}

	return false
}

// SetCreatedBy gets a reference to the given string and assigns it to the CreatedBy field.
func (o *GetRolesResponseBodyItem) SetCreatedBy(v string) {
	o.CreatedBy = &v
}

// GetUpdatedBy returns the UpdatedBy field value if set, zero value otherwise.
func (o *GetRolesResponseBodyItem) GetUpdatedBy() string {
	if o == nil || IsNil(o.UpdatedBy) {
		var ret string
		return ret
	}
	return *o.UpdatedBy
}

// GetUpdatedByOk returns a tuple with the UpdatedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRolesResponseBodyItem) GetUpdatedByOk() (*string, bool) {
	if o == nil || IsNil(o.UpdatedBy) {
		return nil, false
	}
	return o.UpdatedBy, true
}

// HasUpdatedBy returns a boolean if a field has been set.
func (o *GetRolesResponseBodyItem) HasUpdatedBy() bool {
	if o != nil && !IsNil(o.UpdatedBy) {
		return true
	}

	return false
}

// SetUpdatedBy gets a reference to the given string and assigns it to the UpdatedBy field.
func (o *GetRolesResponseBodyItem) SetUpdatedBy(v string) {
	o.UpdatedBy = &v
}

// GetCreateTime returns the CreateTime field value if set, zero value otherwise.
func (o *GetRolesResponseBodyItem) GetCreateTime() string {
	if o == nil || IsNil(o.CreateTime) {
		var ret string
		return ret
	}
	return *o.CreateTime
}

// GetCreateTimeOk returns a tuple with the CreateTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRolesResponseBodyItem) GetCreateTimeOk() (*string, bool) {
	if o == nil || IsNil(o.CreateTime) {
		return nil, false
	}
	return o.CreateTime, true
}

// HasCreateTime returns a boolean if a field has been set.
func (o *GetRolesResponseBodyItem) HasCreateTime() bool {
	if o != nil && !IsNil(o.CreateTime) {
		return true
	}

	return false
}

// SetCreateTime gets a reference to the given string and assigns it to the CreateTime field.
func (o *GetRolesResponseBodyItem) SetCreateTime(v string) {
	o.CreateTime = &v
}

// GetUpdateTime returns the UpdateTime field value if set, zero value otherwise.
func (o *GetRolesResponseBodyItem) GetUpdateTime() string {
	if o == nil || IsNil(o.UpdateTime) {
		var ret string
		return ret
	}
	return *o.UpdateTime
}

// GetUpdateTimeOk returns a tuple with the UpdateTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRolesResponseBodyItem) GetUpdateTimeOk() (*string, bool) {
	if o == nil || IsNil(o.UpdateTime) {
		return nil, false
	}
	return o.UpdateTime, true
}

// HasUpdateTime returns a boolean if a field has been set.
func (o *GetRolesResponseBodyItem) HasUpdateTime() bool {
	if o != nil && !IsNil(o.UpdateTime) {
		return true
	}

	return false
}

// SetUpdateTime gets a reference to the given string and assigns it to the UpdateTime field.
func (o *GetRolesResponseBodyItem) SetUpdateTime(v string) {
	o.UpdateTime = &v
}

// GetRoleName returns the RoleName field value if set, zero value otherwise.
func (o *GetRolesResponseBodyItem) GetRoleName() string {
	if o == nil || IsNil(o.RoleName) {
		var ret string
		return ret
	}
	return *o.RoleName
}

// GetRoleNameOk returns a tuple with the RoleName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRolesResponseBodyItem) GetRoleNameOk() (*string, bool) {
	if o == nil || IsNil(o.RoleName) {
		return nil, false
	}
	return o.RoleName, true
}

// HasRoleName returns a boolean if a field has been set.
func (o *GetRolesResponseBodyItem) HasRoleName() bool {
	if o != nil && !IsNil(o.RoleName) {
		return true
	}

	return false
}

// SetRoleName gets a reference to the given string and assigns it to the RoleName field.
func (o *GetRolesResponseBodyItem) SetRoleName(v string) {
	o.RoleName = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *GetRolesResponseBodyItem) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRolesResponseBodyItem) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *GetRolesResponseBodyItem) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *GetRolesResponseBodyItem) SetDescription(v string) {
	o.Description = &v
}

// GetDisplayName returns the DisplayName field value if set, zero value otherwise.
func (o *GetRolesResponseBodyItem) GetDisplayName() string {
	if o == nil || IsNil(o.DisplayName) {
		var ret string
		return ret
	}
	return *o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRolesResponseBodyItem) GetDisplayNameOk() (*string, bool) {
	if o == nil || IsNil(o.DisplayName) {
		return nil, false
	}
	return o.DisplayName, true
}

// HasDisplayName returns a boolean if a field has been set.
func (o *GetRolesResponseBodyItem) HasDisplayName() bool {
	if o != nil && !IsNil(o.DisplayName) {
		return true
	}

	return false
}

// SetDisplayName gets a reference to the given string and assigns it to the DisplayName field.
func (o *GetRolesResponseBodyItem) SetDisplayName(v string) {
	o.DisplayName = &v
}

// GetDisplayDescription returns the DisplayDescription field value if set, zero value otherwise.
func (o *GetRolesResponseBodyItem) GetDisplayDescription() string {
	if o == nil || IsNil(o.DisplayDescription) {
		var ret string
		return ret
	}
	return *o.DisplayDescription
}

// GetDisplayDescriptionOk returns a tuple with the DisplayDescription field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRolesResponseBodyItem) GetDisplayDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.DisplayDescription) {
		return nil, false
	}
	return o.DisplayDescription, true
}

// HasDisplayDescription returns a boolean if a field has been set.
func (o *GetRolesResponseBodyItem) HasDisplayDescription() bool {
	if o != nil && !IsNil(o.DisplayDescription) {
		return true
	}

	return false
}

// SetDisplayDescription gets a reference to the given string and assigns it to the DisplayDescription field.
func (o *GetRolesResponseBodyItem) SetDisplayDescription(v string) {
	o.DisplayDescription = &v
}

// GetSystemRole returns the SystemRole field value if set, zero value otherwise.
func (o *GetRolesResponseBodyItem) GetSystemRole() bool {
	if o == nil || IsNil(o.SystemRole) {
		var ret bool
		return ret
	}
	return *o.SystemRole
}

// GetSystemRoleOk returns a tuple with the SystemRole field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRolesResponseBodyItem) GetSystemRoleOk() (*bool, bool) {
	if o == nil || IsNil(o.SystemRole) {
		return nil, false
	}
	return o.SystemRole, true
}

// HasSystemRole returns a boolean if a field has been set.
func (o *GetRolesResponseBodyItem) HasSystemRole() bool {
	if o != nil && !IsNil(o.SystemRole) {
		return true
	}

	return false
}

// SetSystemRole gets a reference to the given bool and assigns it to the SystemRole field.
func (o *GetRolesResponseBodyItem) SetSystemRole(v bool) {
	o.SystemRole = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *GetRolesResponseBodyItem) GetStatus() RoleStatus {
	if o == nil || IsNil(o.Status) {
		var ret RoleStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRolesResponseBodyItem) GetStatusOk() (*RoleStatus, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *GetRolesResponseBodyItem) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given RoleStatus and assigns it to the Status field.
func (o *GetRolesResponseBodyItem) SetStatus(v RoleStatus) {
	o.Status = &v
}

// GetPrivileges returns the Privileges field value if set, zero value otherwise.
func (o *GetRolesResponseBodyItem) GetPrivileges() []RolePrivilegeItem {
	if o == nil || IsNil(o.Privileges) {
		var ret []RolePrivilegeItem
		return ret
	}
	return o.Privileges
}

// GetPrivilegesOk returns a tuple with the Privileges field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRolesResponseBodyItem) GetPrivilegesOk() ([]RolePrivilegeItem, bool) {
	if o == nil || IsNil(o.Privileges) {
		return nil, false
	}
	return o.Privileges, true
}

// HasPrivileges returns a boolean if a field has been set.
func (o *GetRolesResponseBodyItem) HasPrivileges() bool {
	if o != nil && !IsNil(o.Privileges) {
		return true
	}

	return false
}

// SetPrivileges gets a reference to the given []RolePrivilegeItem and assigns it to the Privileges field.
func (o *GetRolesResponseBodyItem) SetPrivileges(v []RolePrivilegeItem) {
	o.Privileges = v
}

func (o GetRolesResponseBodyItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetRolesResponseBodyItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.OrgId) {
		toSerialize["orgId"] = o.OrgId
	}
	if !IsNil(o.CreatedBy) {
		toSerialize["createdBy"] = o.CreatedBy
	}
	if !IsNil(o.UpdatedBy) {
		toSerialize["updatedBy"] = o.UpdatedBy
	}
	if !IsNil(o.CreateTime) {
		toSerialize["createTime"] = o.CreateTime
	}
	if !IsNil(o.UpdateTime) {
		toSerialize["updateTime"] = o.UpdateTime
	}
	if !IsNil(o.RoleName) {
		toSerialize["roleName"] = o.RoleName
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.DisplayName) {
		toSerialize["displayName"] = o.DisplayName
	}
	if !IsNil(o.DisplayDescription) {
		toSerialize["displayDescription"] = o.DisplayDescription
	}
	if !IsNil(o.SystemRole) {
		toSerialize["systemRole"] = o.SystemRole
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Privileges) {
		toSerialize["privileges"] = o.Privileges
	}
	return toSerialize, nil
}

type NullableGetRolesResponseBodyItem struct {
	value *GetRolesResponseBodyItem
	isSet bool
}

func (v NullableGetRolesResponseBodyItem) Get() *GetRolesResponseBodyItem {
	return v.value
}

func (v *NullableGetRolesResponseBodyItem) Set(val *GetRolesResponseBodyItem) {
	v.value = val
	v.isSet = true
}

func (v NullableGetRolesResponseBodyItem) IsSet() bool {
	return v.isSet
}

func (v *NullableGetRolesResponseBodyItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetRolesResponseBodyItem(val *GetRolesResponseBodyItem) *NullableGetRolesResponseBodyItem {
	return &NullableGetRolesResponseBodyItem{value: val, isSet: true}
}

func (v NullableGetRolesResponseBodyItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetRolesResponseBodyItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


