/*
Admin API for IDMC

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the LoginResponseBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LoginResponseBody{}

// LoginResponseBody struct for LoginResponseBody
type LoginResponseBody struct {
	// Subscribed Informatica products.
	Products []LoginResponseBodyProduct `json:"products"`
	UserInfo LoginResponseBodyUserInfo `json:"userInfo"`
}

type _LoginResponseBody LoginResponseBody

// NewLoginResponseBody instantiates a new LoginResponseBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLoginResponseBody(products []LoginResponseBodyProduct, userInfo LoginResponseBodyUserInfo) *LoginResponseBody {
	this := LoginResponseBody{}
	this.Products = products
	this.UserInfo = userInfo
	return &this
}

// NewLoginResponseBodyWithDefaults instantiates a new LoginResponseBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLoginResponseBodyWithDefaults() *LoginResponseBody {
	this := LoginResponseBody{}
	return &this
}

// GetProducts returns the Products field value
func (o *LoginResponseBody) GetProducts() []LoginResponseBodyProduct {
	if o == nil {
		var ret []LoginResponseBodyProduct
		return ret
	}

	return o.Products
}

// GetProductsOk returns a tuple with the Products field value
// and a boolean to check if the value has been set.
func (o *LoginResponseBody) GetProductsOk() ([]LoginResponseBodyProduct, bool) {
	if o == nil {
		return nil, false
	}
	return o.Products, true
}

// SetProducts sets field value
func (o *LoginResponseBody) SetProducts(v []LoginResponseBodyProduct) {
	o.Products = v
}

// GetUserInfo returns the UserInfo field value
func (o *LoginResponseBody) GetUserInfo() LoginResponseBodyUserInfo {
	if o == nil {
		var ret LoginResponseBodyUserInfo
		return ret
	}

	return o.UserInfo
}

// GetUserInfoOk returns a tuple with the UserInfo field value
// and a boolean to check if the value has been set.
func (o *LoginResponseBody) GetUserInfoOk() (*LoginResponseBodyUserInfo, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserInfo, true
}

// SetUserInfo sets field value
func (o *LoginResponseBody) SetUserInfo(v LoginResponseBodyUserInfo) {
	o.UserInfo = v
}

func (o LoginResponseBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LoginResponseBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["products"] = o.Products
	toSerialize["userInfo"] = o.UserInfo
	return toSerialize, nil
}

func (o *LoginResponseBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"products",
		"userInfo",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLoginResponseBody := _LoginResponseBody{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLoginResponseBody)

	if err != nil {
		return err
	}

	*o = LoginResponseBody(varLoginResponseBody)

	return err
}

type NullableLoginResponseBody struct {
	value *LoginResponseBody
	isSet bool
}

func (v NullableLoginResponseBody) Get() *LoginResponseBody {
	return v.value
}

func (v *NullableLoginResponseBody) Set(val *LoginResponseBody) {
	v.value = val
	v.isSet = true
}

func (v NullableLoginResponseBody) IsSet() bool {
	return v.isSet
}

func (v *NullableLoginResponseBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLoginResponseBody(val *LoginResponseBody) *NullableLoginResponseBody {
	return &NullableLoginResponseBody{value: val, isSet: true}
}

func (v NullableLoginResponseBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLoginResponseBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


