/*
Admin API for IDMC

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the LoginResponseBodyProduct type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LoginResponseBodyProduct{}

// LoginResponseBodyProduct struct for LoginResponseBodyProduct
type LoginResponseBodyProduct struct {
	// Product name.
	Name string `json:"name"`
	// Base API URL for the product. Use in REST API requests.
	BaseApiUrl string `json:"baseApiUrl"`
}

type _LoginResponseBodyProduct LoginResponseBodyProduct

// NewLoginResponseBodyProduct instantiates a new LoginResponseBodyProduct object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLoginResponseBodyProduct(name string, baseApiUrl string) *LoginResponseBodyProduct {
	this := LoginResponseBodyProduct{}
	this.Name = name
	this.BaseApiUrl = baseApiUrl
	return &this
}

// NewLoginResponseBodyProductWithDefaults instantiates a new LoginResponseBodyProduct object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLoginResponseBodyProductWithDefaults() *LoginResponseBodyProduct {
	this := LoginResponseBodyProduct{}
	return &this
}

// GetName returns the Name field value
func (o *LoginResponseBodyProduct) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *LoginResponseBodyProduct) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *LoginResponseBodyProduct) SetName(v string) {
	o.Name = v
}

// GetBaseApiUrl returns the BaseApiUrl field value
func (o *LoginResponseBodyProduct) GetBaseApiUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BaseApiUrl
}

// GetBaseApiUrlOk returns a tuple with the BaseApiUrl field value
// and a boolean to check if the value has been set.
func (o *LoginResponseBodyProduct) GetBaseApiUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BaseApiUrl, true
}

// SetBaseApiUrl sets field value
func (o *LoginResponseBodyProduct) SetBaseApiUrl(v string) {
	o.BaseApiUrl = v
}

func (o LoginResponseBodyProduct) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LoginResponseBodyProduct) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["baseApiUrl"] = o.BaseApiUrl
	return toSerialize, nil
}

func (o *LoginResponseBodyProduct) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"baseApiUrl",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLoginResponseBodyProduct := _LoginResponseBodyProduct{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLoginResponseBodyProduct)

	if err != nil {
		return err
	}

	*o = LoginResponseBodyProduct(varLoginResponseBodyProduct)

	return err
}

type NullableLoginResponseBodyProduct struct {
	value *LoginResponseBodyProduct
	isSet bool
}

func (v NullableLoginResponseBodyProduct) Get() *LoginResponseBodyProduct {
	return v.value
}

func (v *NullableLoginResponseBodyProduct) Set(val *LoginResponseBodyProduct) {
	v.value = val
	v.isSet = true
}

func (v NullableLoginResponseBodyProduct) IsSet() bool {
	return v.isSet
}

func (v *NullableLoginResponseBodyProduct) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLoginResponseBodyProduct(val *LoginResponseBodyProduct) *NullableLoginResponseBodyProduct {
	return &NullableLoginResponseBodyProduct{value: val, isSet: true}
}

func (v NullableLoginResponseBodyProduct) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLoginResponseBodyProduct) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


