/*
Admin API for IDMC

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateRoleRequestBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateRoleRequestBody{}

// CreateRoleRequestBody struct for CreateRoleRequestBody
type CreateRoleRequestBody struct {
	// IDs of the privileges to assign to the role. A role must have at least one privilege assigned to it.
	Privileges []string `json:"privileges"`
	// Name of the role.
	Name string `json:"name"`
	// Description of the role.
	Description *string `json:"description,omitempty"`
}

type _CreateRoleRequestBody CreateRoleRequestBody

// NewCreateRoleRequestBody instantiates a new CreateRoleRequestBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateRoleRequestBody(privileges []string, name string) *CreateRoleRequestBody {
	this := CreateRoleRequestBody{}
	this.Privileges = privileges
	this.Name = name
	return &this
}

// NewCreateRoleRequestBodyWithDefaults instantiates a new CreateRoleRequestBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateRoleRequestBodyWithDefaults() *CreateRoleRequestBody {
	this := CreateRoleRequestBody{}
	return &this
}

// GetPrivileges returns the Privileges field value
func (o *CreateRoleRequestBody) GetPrivileges() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Privileges
}

// GetPrivilegesOk returns a tuple with the Privileges field value
// and a boolean to check if the value has been set.
func (o *CreateRoleRequestBody) GetPrivilegesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Privileges, true
}

// SetPrivileges sets field value
func (o *CreateRoleRequestBody) SetPrivileges(v []string) {
	o.Privileges = v
}

// GetName returns the Name field value
func (o *CreateRoleRequestBody) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateRoleRequestBody) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateRoleRequestBody) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CreateRoleRequestBody) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateRoleRequestBody) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CreateRoleRequestBody) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CreateRoleRequestBody) SetDescription(v string) {
	o.Description = &v
}

func (o CreateRoleRequestBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateRoleRequestBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["privileges"] = o.Privileges
	toSerialize["name"] = o.Name
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	return toSerialize, nil
}

func (o *CreateRoleRequestBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"privileges",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateRoleRequestBody := _CreateRoleRequestBody{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateRoleRequestBody)

	if err != nil {
		return err
	}

	*o = CreateRoleRequestBody(varCreateRoleRequestBody)

	return err
}

type NullableCreateRoleRequestBody struct {
	value *CreateRoleRequestBody
	isSet bool
}

func (v NullableCreateRoleRequestBody) Get() *CreateRoleRequestBody {
	return v.value
}

func (v *NullableCreateRoleRequestBody) Set(val *CreateRoleRequestBody) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateRoleRequestBody) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateRoleRequestBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateRoleRequestBody(val *CreateRoleRequestBody) *NullableCreateRoleRequestBody {
	return &NullableCreateRoleRequestBody{value: val, isSet: true}
}

func (v NullableCreateRoleRequestBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateRoleRequestBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


