/*
Admin API for IDMC

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the WithPrivilegeRefs type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WithPrivilegeRefs{}

// WithPrivilegeRefs struct for WithPrivilegeRefs
type WithPrivilegeRefs struct {
	// IDs of the privileges to assign to the role. A role must have at least one privilege assigned to it.
	Privileges []string `json:"privileges,omitempty"`
}

// NewWithPrivilegeRefs instantiates a new WithPrivilegeRefs object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWithPrivilegeRefs() *WithPrivilegeRefs {
	this := WithPrivilegeRefs{}
	return &this
}

// NewWithPrivilegeRefsWithDefaults instantiates a new WithPrivilegeRefs object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWithPrivilegeRefsWithDefaults() *WithPrivilegeRefs {
	this := WithPrivilegeRefs{}
	return &this
}

// GetPrivileges returns the Privileges field value if set, zero value otherwise.
func (o *WithPrivilegeRefs) GetPrivileges() []string {
	if o == nil || IsNil(o.Privileges) {
		var ret []string
		return ret
	}
	return o.Privileges
}

// GetPrivilegesOk returns a tuple with the Privileges field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WithPrivilegeRefs) GetPrivilegesOk() ([]string, bool) {
	if o == nil || IsNil(o.Privileges) {
		return nil, false
	}
	return o.Privileges, true
}

// HasPrivileges returns a boolean if a field has been set.
func (o *WithPrivilegeRefs) HasPrivileges() bool {
	if o != nil && !IsNil(o.Privileges) {
		return true
	}

	return false
}

// SetPrivileges gets a reference to the given []string and assigns it to the Privileges field.
func (o *WithPrivilegeRefs) SetPrivileges(v []string) {
	o.Privileges = v
}

func (o WithPrivilegeRefs) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WithPrivilegeRefs) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Privileges) {
		toSerialize["privileges"] = o.Privileges
	}
	return toSerialize, nil
}

type NullableWithPrivilegeRefs struct {
	value *WithPrivilegeRefs
	isSet bool
}

func (v NullableWithPrivilegeRefs) Get() *WithPrivilegeRefs {
	return v.value
}

func (v *NullableWithPrivilegeRefs) Set(val *WithPrivilegeRefs) {
	v.value = val
	v.isSet = true
}

func (v NullableWithPrivilegeRefs) IsSet() bool {
	return v.isSet
}

func (v *NullableWithPrivilegeRefs) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWithPrivilegeRefs(val *WithPrivilegeRefs) *NullableWithPrivilegeRefs {
	return &NullableWithPrivilegeRefs{value: val, isSet: true}
}

func (v NullableWithPrivilegeRefs) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWithPrivilegeRefs) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


