/*
Admin API for IDMC

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateRoleRequestBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateRoleRequestBody{}

// UpdateRoleRequestBody struct for UpdateRoleRequestBody
type UpdateRoleRequestBody struct {
	// IDs of the privileges to assign to the role. A role must have at least one privilege assigned to it.
	Privileges []string `json:"privileges"`
}

type _UpdateRoleRequestBody UpdateRoleRequestBody

// NewUpdateRoleRequestBody instantiates a new UpdateRoleRequestBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateRoleRequestBody(privileges []string) *UpdateRoleRequestBody {
	this := UpdateRoleRequestBody{}
	this.Privileges = privileges
	return &this
}

// NewUpdateRoleRequestBodyWithDefaults instantiates a new UpdateRoleRequestBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateRoleRequestBodyWithDefaults() *UpdateRoleRequestBody {
	this := UpdateRoleRequestBody{}
	return &this
}

// GetPrivileges returns the Privileges field value
func (o *UpdateRoleRequestBody) GetPrivileges() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Privileges
}

// GetPrivilegesOk returns a tuple with the Privileges field value
// and a boolean to check if the value has been set.
func (o *UpdateRoleRequestBody) GetPrivilegesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Privileges, true
}

// SetPrivileges sets field value
func (o *UpdateRoleRequestBody) SetPrivileges(v []string) {
	o.Privileges = v
}

func (o UpdateRoleRequestBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateRoleRequestBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["privileges"] = o.Privileges
	return toSerialize, nil
}

func (o *UpdateRoleRequestBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"privileges",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateRoleRequestBody := _UpdateRoleRequestBody{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateRoleRequestBody)

	if err != nil {
		return err
	}

	*o = UpdateRoleRequestBody(varUpdateRoleRequestBody)

	return err
}

type NullableUpdateRoleRequestBody struct {
	value *UpdateRoleRequestBody
	isSet bool
}

func (v NullableUpdateRoleRequestBody) Get() *UpdateRoleRequestBody {
	return v.value
}

func (v *NullableUpdateRoleRequestBody) Set(val *UpdateRoleRequestBody) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateRoleRequestBody) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateRoleRequestBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateRoleRequestBody(val *UpdateRoleRequestBody) *NullableUpdateRoleRequestBody {
	return &NullableUpdateRoleRequestBody{value: val, isSet: true}
}

func (v NullableUpdateRoleRequestBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateRoleRequestBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


