/*
Admin API for IDMC

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the LoginRequestBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LoginRequestBody{}

// LoginRequestBody struct for LoginRequestBody
type LoginRequestBody struct {
	// Informatica Intelligent Cloud Services user name for the organization that you want to log in to.
	Username string `json:"username"`
	// Informatica Intelligent Cloud Services password.
	Password string `json:"password"`
}

type _LoginRequestBody LoginRequestBody

// NewLoginRequestBody instantiates a new LoginRequestBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLoginRequestBody(username string, password string) *LoginRequestBody {
	this := LoginRequestBody{}
	this.Username = username
	this.Password = password
	return &this
}

// NewLoginRequestBodyWithDefaults instantiates a new LoginRequestBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLoginRequestBodyWithDefaults() *LoginRequestBody {
	this := LoginRequestBody{}
	return &this
}

// GetUsername returns the Username field value
func (o *LoginRequestBody) GetUsername() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Username
}

// GetUsernameOk returns a tuple with the Username field value
// and a boolean to check if the value has been set.
func (o *LoginRequestBody) GetUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Username, true
}

// SetUsername sets field value
func (o *LoginRequestBody) SetUsername(v string) {
	o.Username = v
}

// GetPassword returns the Password field value
func (o *LoginRequestBody) GetPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Password
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
func (o *LoginRequestBody) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Password, true
}

// SetPassword sets field value
func (o *LoginRequestBody) SetPassword(v string) {
	o.Password = v
}

func (o LoginRequestBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LoginRequestBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["username"] = o.Username
	toSerialize["password"] = o.Password
	return toSerialize, nil
}

func (o *LoginRequestBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"username",
		"password",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLoginRequestBody := _LoginRequestBody{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLoginRequestBody)

	if err != nil {
		return err
	}

	*o = LoginRequestBody(varLoginRequestBody)

	return err
}

type NullableLoginRequestBody struct {
	value *LoginRequestBody
	isSet bool
}

func (v NullableLoginRequestBody) Get() *LoginRequestBody {
	return v.value
}

func (v *NullableLoginRequestBody) Set(val *LoginRequestBody) {
	v.value = val
	v.isSet = true
}

func (v NullableLoginRequestBody) IsSet() bool {
	return v.isSet
}

func (v *NullableLoginRequestBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLoginRequestBody(val *LoginRequestBody) *NullableLoginRequestBody {
	return &NullableLoginRequestBody{value: val, isSet: true}
}

func (v NullableLoginRequestBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLoginRequestBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


