/*
Admin API for IDMC

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the WithPrivilegeItems type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WithPrivilegeItems{}

// WithPrivilegeItems struct for WithPrivilegeItems
type WithPrivilegeItems struct {
	Privileges []RolePrivilegeItem `json:"privileges,omitempty"`
}

// NewWithPrivilegeItems instantiates a new WithPrivilegeItems object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWithPrivilegeItems() *WithPrivilegeItems {
	this := WithPrivilegeItems{}
	return &this
}

// NewWithPrivilegeItemsWithDefaults instantiates a new WithPrivilegeItems object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWithPrivilegeItemsWithDefaults() *WithPrivilegeItems {
	this := WithPrivilegeItems{}
	return &this
}

// GetPrivileges returns the Privileges field value if set, zero value otherwise.
func (o *WithPrivilegeItems) GetPrivileges() []RolePrivilegeItem {
	if o == nil || IsNil(o.Privileges) {
		var ret []RolePrivilegeItem
		return ret
	}
	return o.Privileges
}

// GetPrivilegesOk returns a tuple with the Privileges field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WithPrivilegeItems) GetPrivilegesOk() ([]RolePrivilegeItem, bool) {
	if o == nil || IsNil(o.Privileges) {
		return nil, false
	}
	return o.Privileges, true
}

// HasPrivileges returns a boolean if a field has been set.
func (o *WithPrivilegeItems) HasPrivileges() bool {
	if o != nil && !IsNil(o.Privileges) {
		return true
	}

	return false
}

// SetPrivileges gets a reference to the given []RolePrivilegeItem and assigns it to the Privileges field.
func (o *WithPrivilegeItems) SetPrivileges(v []RolePrivilegeItem) {
	o.Privileges = v
}

func (o WithPrivilegeItems) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WithPrivilegeItems) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Privileges) {
		toSerialize["privileges"] = o.Privileges
	}
	return toSerialize, nil
}

type NullableWithPrivilegeItems struct {
	value *WithPrivilegeItems
	isSet bool
}

func (v NullableWithPrivilegeItems) Get() *WithPrivilegeItems {
	return v.value
}

func (v *NullableWithPrivilegeItems) Set(val *WithPrivilegeItems) {
	v.value = val
	v.isSet = true
}

func (v NullableWithPrivilegeItems) IsSet() bool {
	return v.isSet
}

func (v *NullableWithPrivilegeItems) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWithPrivilegeItems(val *WithPrivilegeItems) *NullableWithPrivilegeItems {
	return &NullableWithPrivilegeItems{value: val, isSet: true}
}

func (v NullableWithPrivilegeItems) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWithPrivilegeItems) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


