/*
Admin API for IDMC

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ApiErrorDetail type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiErrorDetail{}

// ApiErrorDetail struct for ApiErrorDetail
type ApiErrorDetail struct {
	Code string `json:"code"`
	Message string `json:"message"`
	DebugMessage *string `json:"debugMessage,omitempty"`
}

type _ApiErrorDetail ApiErrorDetail

// NewApiErrorDetail instantiates a new ApiErrorDetail object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiErrorDetail(code string, message string) *ApiErrorDetail {
	this := ApiErrorDetail{}
	this.Code = code
	this.Message = message
	return &this
}

// NewApiErrorDetailWithDefaults instantiates a new ApiErrorDetail object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiErrorDetailWithDefaults() *ApiErrorDetail {
	this := ApiErrorDetail{}
	return &this
}

// GetCode returns the Code field value
func (o *ApiErrorDetail) GetCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *ApiErrorDetail) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *ApiErrorDetail) SetCode(v string) {
	o.Code = v
}

// GetMessage returns the Message field value
func (o *ApiErrorDetail) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *ApiErrorDetail) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *ApiErrorDetail) SetMessage(v string) {
	o.Message = v
}

// GetDebugMessage returns the DebugMessage field value if set, zero value otherwise.
func (o *ApiErrorDetail) GetDebugMessage() string {
	if o == nil || IsNil(o.DebugMessage) {
		var ret string
		return ret
	}
	return *o.DebugMessage
}

// GetDebugMessageOk returns a tuple with the DebugMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiErrorDetail) GetDebugMessageOk() (*string, bool) {
	if o == nil || IsNil(o.DebugMessage) {
		return nil, false
	}
	return o.DebugMessage, true
}

// HasDebugMessage returns a boolean if a field has been set.
func (o *ApiErrorDetail) HasDebugMessage() bool {
	if o != nil && !IsNil(o.DebugMessage) {
		return true
	}

	return false
}

// SetDebugMessage gets a reference to the given string and assigns it to the DebugMessage field.
func (o *ApiErrorDetail) SetDebugMessage(v string) {
	o.DebugMessage = &v
}

func (o ApiErrorDetail) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiErrorDetail) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["code"] = o.Code
	toSerialize["message"] = o.Message
	if !IsNil(o.DebugMessage) {
		toSerialize["debugMessage"] = o.DebugMessage
	}
	return toSerialize, nil
}

func (o *ApiErrorDetail) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"code",
		"message",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiErrorDetail := _ApiErrorDetail{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApiErrorDetail)

	if err != nil {
		return err
	}

	*o = ApiErrorDetail(varApiErrorDetail)

	return err
}

type NullableApiErrorDetail struct {
	value *ApiErrorDetail
	isSet bool
}

func (v NullableApiErrorDetail) Get() *ApiErrorDetail {
	return v.value
}

func (v *NullableApiErrorDetail) Set(val *ApiErrorDetail) {
	v.value = val
	v.isSet = true
}

func (v NullableApiErrorDetail) IsSet() bool {
	return v.isSet
}

func (v *NullableApiErrorDetail) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiErrorDetail(val *ApiErrorDetail) *NullableApiErrorDetail {
	return &NullableApiErrorDetail{value: val, isSet: true}
}

func (v NullableApiErrorDetail) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiErrorDetail) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


