/*
Admin API for IDMC

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RolePrivilegeItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RolePrivilegeItem{}

// RolePrivilegeItem struct for RolePrivilegeItem
type RolePrivilegeItem struct {
	// Privilege ID.
	Id string `json:"id"`
	// Name of the privilege.
	Name string `json:"name"`
	// Description of the privilege.
	Description *string `json:"description,omitempty"`
	// The Informatica Intelligent Cloud Services service that applies to the privilege.
	Service string `json:"service"`
	// Status of the privilege. Returns one of the following values: * Enabled: License to use the privilege is valid. * Disabled: License to use the privilege has expired. * Unassigned: No license to use this privilege. * Default: Privilege included by default.
	Status string `json:"status"`
}

type _RolePrivilegeItem RolePrivilegeItem

// NewRolePrivilegeItem instantiates a new RolePrivilegeItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRolePrivilegeItem(id string, name string, service string, status string) *RolePrivilegeItem {
	this := RolePrivilegeItem{}
	this.Id = id
	this.Name = name
	this.Service = service
	this.Status = status
	return &this
}

// NewRolePrivilegeItemWithDefaults instantiates a new RolePrivilegeItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRolePrivilegeItemWithDefaults() *RolePrivilegeItem {
	this := RolePrivilegeItem{}
	return &this
}

// GetId returns the Id field value
func (o *RolePrivilegeItem) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *RolePrivilegeItem) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *RolePrivilegeItem) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *RolePrivilegeItem) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *RolePrivilegeItem) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *RolePrivilegeItem) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *RolePrivilegeItem) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RolePrivilegeItem) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *RolePrivilegeItem) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *RolePrivilegeItem) SetDescription(v string) {
	o.Description = &v
}

// GetService returns the Service field value
func (o *RolePrivilegeItem) GetService() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Service
}

// GetServiceOk returns a tuple with the Service field value
// and a boolean to check if the value has been set.
func (o *RolePrivilegeItem) GetServiceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Service, true
}

// SetService sets field value
func (o *RolePrivilegeItem) SetService(v string) {
	o.Service = v
}

// GetStatus returns the Status field value
func (o *RolePrivilegeItem) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *RolePrivilegeItem) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *RolePrivilegeItem) SetStatus(v string) {
	o.Status = v
}

func (o RolePrivilegeItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RolePrivilegeItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	toSerialize["service"] = o.Service
	toSerialize["status"] = o.Status
	return toSerialize, nil
}

func (o *RolePrivilegeItem) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"service",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRolePrivilegeItem := _RolePrivilegeItem{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRolePrivilegeItem)

	if err != nil {
		return err
	}

	*o = RolePrivilegeItem(varRolePrivilegeItem)

	return err
}

type NullableRolePrivilegeItem struct {
	value *RolePrivilegeItem
	isSet bool
}

func (v NullableRolePrivilegeItem) Get() *RolePrivilegeItem {
	return v.value
}

func (v *NullableRolePrivilegeItem) Set(val *RolePrivilegeItem) {
	v.value = val
	v.isSet = true
}

func (v NullableRolePrivilegeItem) IsSet() bool {
	return v.isSet
}

func (v *NullableRolePrivilegeItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRolePrivilegeItem(val *RolePrivilegeItem) *NullableRolePrivilegeItem {
	return &NullableRolePrivilegeItem{value: val, isSet: true}
}

func (v NullableRolePrivilegeItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRolePrivilegeItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


