/*
Admin API for IDMC

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the LoginResponseBodyUserInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LoginResponseBodyUserInfo{}

// LoginResponseBodyUserInfo struct for LoginResponseBodyUserInfo
type LoginResponseBodyUserInfo struct {
	// REST API session ID for the current session. Use in most REST API request headers.
	SessionId string `json:"sessionId"`
	// User ID.
	Id string `json:"id"`
	// User name.
	Name string `json:"name"`
	// Organization ID for the parent.
	ParentOrgId string `json:"parentOrgId"`
	// ID of the organization the user belongs to.
	OrgId string `json:"orgId"`
	// Organization name.
	OrgName string `json:"orgName"`
	// User group information for the user.
	Groups map[string]interface{} `json:"groups"`
	// Status of the user.
	Status string `json:"status"`
}

type _LoginResponseBodyUserInfo LoginResponseBodyUserInfo

// NewLoginResponseBodyUserInfo instantiates a new LoginResponseBodyUserInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLoginResponseBodyUserInfo(sessionId string, id string, name string, parentOrgId string, orgId string, orgName string, groups map[string]interface{}, status string) *LoginResponseBodyUserInfo {
	this := LoginResponseBodyUserInfo{}
	this.SessionId = sessionId
	this.Id = id
	this.Name = name
	this.ParentOrgId = parentOrgId
	this.OrgId = orgId
	this.OrgName = orgName
	this.Groups = groups
	this.Status = status
	return &this
}

// NewLoginResponseBodyUserInfoWithDefaults instantiates a new LoginResponseBodyUserInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLoginResponseBodyUserInfoWithDefaults() *LoginResponseBodyUserInfo {
	this := LoginResponseBodyUserInfo{}
	return &this
}

// GetSessionId returns the SessionId field value
func (o *LoginResponseBodyUserInfo) GetSessionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SessionId
}

// GetSessionIdOk returns a tuple with the SessionId field value
// and a boolean to check if the value has been set.
func (o *LoginResponseBodyUserInfo) GetSessionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SessionId, true
}

// SetSessionId sets field value
func (o *LoginResponseBodyUserInfo) SetSessionId(v string) {
	o.SessionId = v
}

// GetId returns the Id field value
func (o *LoginResponseBodyUserInfo) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *LoginResponseBodyUserInfo) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *LoginResponseBodyUserInfo) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *LoginResponseBodyUserInfo) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *LoginResponseBodyUserInfo) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *LoginResponseBodyUserInfo) SetName(v string) {
	o.Name = v
}

// GetParentOrgId returns the ParentOrgId field value
func (o *LoginResponseBodyUserInfo) GetParentOrgId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ParentOrgId
}

// GetParentOrgIdOk returns a tuple with the ParentOrgId field value
// and a boolean to check if the value has been set.
func (o *LoginResponseBodyUserInfo) GetParentOrgIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ParentOrgId, true
}

// SetParentOrgId sets field value
func (o *LoginResponseBodyUserInfo) SetParentOrgId(v string) {
	o.ParentOrgId = v
}

// GetOrgId returns the OrgId field value
func (o *LoginResponseBodyUserInfo) GetOrgId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrgId
}

// GetOrgIdOk returns a tuple with the OrgId field value
// and a boolean to check if the value has been set.
func (o *LoginResponseBodyUserInfo) GetOrgIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrgId, true
}

// SetOrgId sets field value
func (o *LoginResponseBodyUserInfo) SetOrgId(v string) {
	o.OrgId = v
}

// GetOrgName returns the OrgName field value
func (o *LoginResponseBodyUserInfo) GetOrgName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrgName
}

// GetOrgNameOk returns a tuple with the OrgName field value
// and a boolean to check if the value has been set.
func (o *LoginResponseBodyUserInfo) GetOrgNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrgName, true
}

// SetOrgName sets field value
func (o *LoginResponseBodyUserInfo) SetOrgName(v string) {
	o.OrgName = v
}

// GetGroups returns the Groups field value
func (o *LoginResponseBodyUserInfo) GetGroups() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Groups
}

// GetGroupsOk returns a tuple with the Groups field value
// and a boolean to check if the value has been set.
func (o *LoginResponseBodyUserInfo) GetGroupsOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Groups, true
}

// SetGroups sets field value
func (o *LoginResponseBodyUserInfo) SetGroups(v map[string]interface{}) {
	o.Groups = v
}

// GetStatus returns the Status field value
func (o *LoginResponseBodyUserInfo) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *LoginResponseBodyUserInfo) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *LoginResponseBodyUserInfo) SetStatus(v string) {
	o.Status = v
}

func (o LoginResponseBodyUserInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LoginResponseBodyUserInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["sessionId"] = o.SessionId
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["parentOrgId"] = o.ParentOrgId
	toSerialize["orgId"] = o.OrgId
	toSerialize["orgName"] = o.OrgName
	toSerialize["groups"] = o.Groups
	toSerialize["status"] = o.Status
	return toSerialize, nil
}

func (o *LoginResponseBodyUserInfo) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"sessionId",
		"id",
		"name",
		"parentOrgId",
		"orgId",
		"orgName",
		"groups",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLoginResponseBodyUserInfo := _LoginResponseBodyUserInfo{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLoginResponseBodyUserInfo)

	if err != nil {
		return err
	}

	*o = LoginResponseBodyUserInfo(varLoginResponseBodyUserInfo)

	return err
}

type NullableLoginResponseBodyUserInfo struct {
	value *LoginResponseBodyUserInfo
	isSet bool
}

func (v NullableLoginResponseBodyUserInfo) Get() *LoginResponseBodyUserInfo {
	return v.value
}

func (v *NullableLoginResponseBodyUserInfo) Set(val *LoginResponseBodyUserInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableLoginResponseBodyUserInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableLoginResponseBodyUserInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLoginResponseBodyUserInfo(val *LoginResponseBodyUserInfo) *NullableLoginResponseBodyUserInfo {
	return &NullableLoginResponseBodyUserInfo{value: val, isSet: true}
}

func (v NullableLoginResponseBodyUserInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLoginResponseBodyUserInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


